### ISSUE TITLE
Package roadmap

### ISSUE THREAD

**Issue by gdalle** [gdalle/GraphsOptim.jl#14]
**Polynomial problems**

- [x] shortest path
- [x] flow
- [ ] assignment / matching
- [ ] spanning tree

**NP-hard problems**

- [ ] coloring
- [ ] fractional coloring  (see #5)
- [ ] vertex / edge cover
- [ ] maximum clique / independent set
- [ ] traveling salesperson
- [ ] graph isomorphism

See also:

- https://github.com/JuliaGraphs/Graphs.jl/issues/108
